format = """
$os\
$conda\
$username\
$hostname\
$directory\
$git_branch\
$git_state\
$git_status\
$c\
$golang\
$haskell\
$julia\
$nim\
$rust\
$python\
$zig\
$ocaml\
$docker_context\
$line_break\
$character"""

add_newline=false
command_timeout = 10000

[os]
disabled = false

[os.symbols]
Debian = "  "

[directory]
style = "blue"
home_symbol = ""

[directory.substitutions]
"Documents" = "󰈙  "
"Downloads" = "  "
"Music" = "  "
"Pictures" = "  " 

[c]
symbol = "  "
format = '[ $symbol ($version) ]($style)'
style = "italic bright-blue"

[docker_context]
symbol = "  "
style = "bg:#06969A"
format = '[ $symbol $context ]($style)'

[golang]
symbol = "  "
format = '[ $symbol ($version) ]($style)'
style = "italic bright-blue"

[haskell]
symbol = "  "
format = '[ $symbol ($version) ]($style)'

[julia]
symbol = "  "
format = '[ $symbol ($version) ]($style)'

[nim]
symbol = "󰆥  "
format = '[ $symbol ($version) ]($style)'

[rust]
symbol = "  "
format = '[ $symbol ($version) ]($style)'

[python]
format = "[ ${symbol} ${version}]($style)"
symbol = "  "
version_format = "${major}.${minor}"
style = "italic bright-yellow"

[zig]
symbol = "  "

[character]
success_symbol = "[❯](purple)"
error_symbol = "[❯](red)"
vimcmd_symbol = "[❮](green)"

[git_branch]
symbol = " "
format = "[$branch]($style)"
style = "bright-black"

[git_status]
format = "[[(*$conflicted$untracked$modified$staged$renamed$deleted)](218) ($ahead_behind$stashed)]($style)"
style = "cyan"
conflicted = "​"
untracked = "​"
modified = "​"
staged = "​"
renamed = "​"
deleted = "​"
stashed = "≡ "

[git_state]
format = '\([$state( $progress_current/$progress_total)]($style)\) '
style = "bright-black"

[cmd_duration]
format = "[$duration]($style) "
style = "yellow"

[ocaml]
symbol = "  "

[conda]
style = "bold green"
symbol = "  "
format = '[$symbol$environment]($style) '
ignore_base = false


[hostname]
ssh_symbol = "  "
